title: Subterranean District
description: The district beneath the surface.
markdown: kramdown
permalink: /:categories/:title/

# Important for project sites (repo pages)
baseurl: "/subterranean-district"

header_pages:
  - manifesto.md
  - archive.md
  - about.md
