title: Subterranean District
description: The district beneath the surface.
theme: minima
markdown: kramdown
permalink: /:categories/:title/

# Tell Minima we want a quieter header (we'll take control of hierarchy)
minima:
  skin: dark

header_pages:
  - manifesto.md
  - archive.md
  - about.md
